# Generated by Django 2.1.4 on 2019-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='auto_range',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='max',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='min',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
