# Generated by Django 2.1.4 on 2019-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_slot_delta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='slot',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
