# Generated by Django 2.1.4 on 2019-02-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20190220_1731'),
        ('starter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShutdownThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Slot')),
            ],
        ),
    ]
